[build]
command = "npm install && npm run build"
python_version = "3.9"

[build.environment]
NODE_VERSION = "18"
PYTHON_ENABLE_WHEEL_CACHE = "1"
PIP_DISABLE_PIP_VERSION_CHECK = "1"
PIP_NO_CLEAN = "1"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
