[build]
command = "pip install -r requirements.txt.lock && gunicorn app:app --workers 2"
python_version = "3.9"

[build.environment]
PYTHON_ENABLE_WHEEL_CACHE = "1"
PIP_DISABLE_PIP_VERSION_CHECK = "1"
PIP_NO_CLEAN = "1"
